//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Egzemplarz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Egzemplarz()
        {
            this.Wypozyczenies = new HashSet<Wypozyczenie>();
        }

        [Required(ErrorMessage = "Pole IdEgzemplarz nie mo¿e byæ puste!")]
        public int IdEgzemplarz { get; set; }

        [Required(ErrorMessage = "Pole IdKsi¹¿ka nie mo¿e byæ puste!")]
        public Nullable<int> IdKsiazka { get; set; }
    

        public virtual Ksiazka Ksiazka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypozyczenie> Wypozyczenies { get; set; }
    }
}
