//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BibliotekaEntities : DbContext
    {
        public BibliotekaEntities()
            : base("name=BibliotekaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autor> Autors { get; set; }
        public virtual DbSet<Czytelnik> Czytelniks { get; set; }
        public virtual DbSet<Egzemplarz> Egzemplarzs { get; set; }
        public virtual DbSet<Gatunek> Gatuneks { get; set; }
        public virtual DbSet<Ksiazka> Ksiazkas { get; set; }
        public virtual DbSet<Wydawnictwo> Wydawnictwoes { get; set; }
        public virtual DbSet<Wypozyczenie> Wypozyczenies { get; set; }
    }
}
