//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Gatunek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gatunek()
        {
            this.Ksiazkas = new HashSet<Ksiazka>();
        }

        [RegularExpression(@"[1-9][0-9]*", ErrorMessage = "Pole IdGatunek musi byæ liczb¹ wiêksz¹ od zera!")]
        [Required(ErrorMessage = "Pole IdGatunek nie mo¿e byæ puste!")]
        public int IdGatunek { get; set; }

        [RegularExpression(@"([A-Za-z]+\s?)+", ErrorMessage = "Pole Nazwa musi byæ zbiorem liter i spacji!")]
        [Required(ErrorMessage = "Pole Nazwa nie mo¿e byæ puste!")]
        [MinLength(3, ErrorMessage = "Minimalna d³ugoœæ pola Nazwa wynosi 3.")]
        public string Nazwa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ksiazka> Ksiazkas { get; set; }
    }
}
