//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ksiazka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ksiazka()
        {
            this.Egzemplarzs = new HashSet<Egzemplarz>();
            this.Autors = new HashSet<Autor>();
        }

        [Required(ErrorMessage = "Pole IdKsiazka nie mo¿e byæ puste!")]
        public int IdKsiazka { get; set; }

        [Required(ErrorMessage = "Pole IdWydawnictwo nie mo¿e byæ puste!")]
        public Nullable<int> IdWydawnictwo { get; set; }

        [Required(ErrorMessage = "Pole IdGatunek nie mo¿e byæ puste!")]
        public Nullable<int> IdGatunek { get; set; }

        [Required(ErrorMessage = "Pole Tytul nie mo¿e byæ puste!")]
        [MinLength(3, ErrorMessage = "Minimalna d³ugoœæ pola Tytu³ wynosi 3.")]
        public string Tytul { get; set; }

        [Required(ErrorMessage = "Pole RokWydania nie mo¿e byæ puste!")]
        [Range(1, 2018, ErrorMessage = "Rok wydania musi byæ wiêkszy ni¿ 0 i mniejszy ni¿ 2019.")]
        public int RokWydania { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Egzemplarz> Egzemplarzs { get; set; }
        public virtual Gatunek Gatunek { get; set; }
        public virtual Wydawnictwo Wydawnictwo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Autor> Autors { get; set; }
    }
}
