//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ksiegozbior
    {
        public string ImieAutora { get; set; }
        public string NazwiskoAutora { get; set; }
        public string Tytul { get; set; }
        public int RokWydania { get; set; }
        public string NazwaWydawnictwa { get; set; }
        public Nullable<int> LiczbaEgzemplarzy { get; set; }
    }
}
