//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wypozyczenie
    {
        public int IdWypozyczenie { get; set; }
        public Nullable<int> IdEgzemplarz { get; set; }
        public Nullable<int> IdCzytelnik { get; set; }
        public bool CzyOddane { get; set; }
        public System.DateTime TerminWypozyczenia { get; set; }
        public System.DateTime TerminOddania { get; set; }
        public int Wersja { get; set; }
    
        public virtual Czytelnik Czytelnik { get; set; }
        public virtual Egzemplarz Egzemplarz { get; set; }
    }
}
